# Generated by Django 4.2.10 on 2024-05-01 20:36

import clothes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип одежды',
                'verbose_name_plural': 'Тип одежды',
            },
        ),
        migrations.CreateModel(
            name='Garderob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=clothes.models.user_directory_path)),
                ('garderob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.garderob')),
                ('type_clothes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clothes.typeclothes')),
            ],
        ),
    ]
