# Generated by Django 4.2.10 on 2024-05-11 11:37

from django.db import migrations


def fill_colors(app_model, schema_editor):
    Colors = app_model.get_model('clothes', 'Colors')
    colors = (
        "White",
        "Black",
        "Red",
        "Yellow",
        "Green",
        "Blue",
        "Orange",
        "Purple",
        "Multi",
        "Brown",
    )

    Colors.objects.bulk_create(
        Colors(
            name=color_name
        ) for color_name in colors
    )


class Migration(migrations.Migration):
    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_colors)
    ]
