# Generated by Django 4.2.10 on 2024-05-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeclothes',
            name='type',
            field=models.CharField(choices=[('low', 'Low'), ('middle', 'Middle'), ('high', 'High')], default='middle', max_length=100),
        ),
    ]
