# Generated by Django 4.2.10 on 2024-05-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_typeclothes_type'),
    ]

    operations = [
    ]
