# Generated by Django 4.2.10 on 2024-05-11 12:18

from django.db import migrations

from clothes.models import ClothesLevel


def fill_type_clothes(app_model, schema_editor):
    TypeClothes = app_model.get_model('clothes', 'TypeClothes')

    type_clothes = {
        ClothesLevel.SHOES: [
            "Jackpots",
            "Jodhpurs",
            "Sneakers",
            "Crocs",
            "Sneakers",
            "Louboutins",
            "Boats",
            "Loafers",
            "Moon rovers",
            "Mary Jane",
            "Moccasins",
            "The Monks",
            "Mules",
            "Soap dishes",
            "Oxfords",
            "Pantolets",
            "Bullets",
            "Readings",
            "Clogs",
            "Sandals",
            "Cossack boots",
            "Cowboy boots",
            "Boots - stockings",
            "Sleepers",
            "Slip - ons",
            "Sneakers",
            "Stilettos",
            "Tennis shoes",
            "Timberlands",
            "Topsiders",
            "Tango Shoes",
            "Shoes - gloves",
            "Ugg boots",
            "Hackers",
            "Chakka",
            "Chelsea",
            "Czechs",
            "Espadrilles",
            "Yacht shoes",
        ],
        ClothesLevel.LEGS: [
            "Shorts",
            "Jeans",
            "Rain pants",
        ],
        ClothesLevel.BODY: [
            "Shorts",
            "Dress",
            "Afghani",
            "Buggy",
            "Bumsters",
            "Bananas",
            "Bermuda",
            "Boyfriends",
            "Breeches",
            "Jeans",
            "Joggers",
            "Pipes",
            "Capri",
            "Cargo",
            "Carrot",
            "Classic",
            "Flared",
            "Leggings",
            "Skinny",
            "Slacks",
            "Pipes",
            "Chinos",
            "Bloomers",
            "Culottes",
            "The Palazzo",
            "Gaucho",
            "Churidary",
            "Skirt",
        ],
        ClothesLevel.HEAD: [
            "Hats",
            "Caps",
            "Bonnets",
            "Helmets",
            "Hoods",
            "Headbands",
            "headscarves",
            "wimples",
            "Masks",
            "Veils",
            "Other headdress",
        ],
    }
    arr = []
    for level in type_clothes.keys():
        arr.extend([(level, name) for name in type_clothes[level]])
    TypeClothes.objects.bulk_create(
        TypeClothes(
            name=name,
            level=level,
        ) for level, name in arr
    )


class Migration(migrations.Migration):
    dependencies = [
        ('clothes', '0003_fill_seasons'),
    ]

    operations = [
        migrations.RunPython(fill_type_clothes)
    ]
